[package]
name = "expressways-client"
authors.workspace = true
description = "Rust client SDK and command-line tools for Expressways"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
expressways-audit = { path = "../expressways-audit" }
expressways-auth = { path = "../expressways-auth" }
expressways-protocol = { path = "../expressways-protocol" }
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
clap.workspace = true
futures-util.workspace = true
hex.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls"] }
uuid.workspace = true
